[gha] fix prepare action to use docker image preinstalled tooling, fix matches logic with invert capability.
Closes: #7171

diff --git a/.github/actions/matches/action.yml b/.github/actions/matches/action.yml
--- a/.github/actions/matches/action.yml
+++ b/.github/actions/matches/action.yml
@@ -12,6 +12,10 @@ inputs:
   pattern:
     description: A grep match pattern used to find changes, must excape quotes (") if they occur in the file name...  why would you do that?.
     required: true
+  invert:
+    description: invert the grep search, "true" or "false"
+    required: false
+    default: "false"
 outputs:
   changes-found:
     description: true if the pattern matched any files.
@@ -25,26 +29,32 @@ runs:
         echo Action parameter file changes_file=$CHANGES_FILE 1>&2
         TARGET_FILE=
         if [[ -n "${CHANGES_CHANGED_FILE_OUTPUTFILE}" ]]; then
-           TARGET_FILE=$CHANGED_FILE_OUTPUTFILE
+          TARGET_FILE="$CHANGES_CHANGED_FILE_OUTPUTFILE"
         fi
-        if [[ -n "${CHANGES_FILE}" ]]; then
-           TARGET_FILE=${CHANGES_FILE}
+        if [[ -n "${CHANGES_FILE}" ]] && [[ -f "${CHANGES_FILE}" ]]; then
+          TARGET_FILE="${CHANGES_FILE}"
         fi
-        result=false
+        set -x
+        INV=""
+        if [[ "${INVERT}" == "true" ]]; then
+          INV="-v"
+        fi
+        result=true
         echo Target File: "${TARGET_FILE}" 1>&2
         echo PATTERN="${PATTERN}" 1>&2
         if [[ -f "${TARGET_FILE}" ]]; then
           echo found: 1>&2
-          cat "${TARGET_FILE}" | grep "${PATTERN}" || echo No matching files. 1>&2
-          count="$( cat "${TARGET_FILE}" | grep -c "${PATTERN}" )" || true
-          if [[ "$count" > 0 ]]; then
-            result=true
+          cat "${TARGET_FILE}" | grep "${INV}" "${PATTERN}" || echo No matching files. 1>&2
+          count="$( cat "${TARGET_FILE}" | grep -c "${INV}" "${PATTERN}" )" || true
+          if [[ "$count" == 0 ]]; then
+            result=false
           fi
         else
-          echo No file specified or found on file system, assume changes occurred. 1>&2
+          echo "::error::Target File was not set or was not found, will assume a change exists.   This is an error that should be corrected."
         fi
         echo "::set-output name=changes::$(echo $result)"
       shell: bash
       env:
         CHANGES_FILE: ${{ inputs.changes-file }}
         PATTERN: ${{ inputs.pattern }}
+        INVERT: ${{ inputs.invert }}
