[WIP] k8s test

diff --git a/scripts/cti b/scripts/cti
--- a/scripts/cti
+++ b/scripts/cti
@@ -16,7 +16,7 @@ EXIT_CODE=0
 # Default timeout is 45 mins
 TIMEOUT_SECS=2700
 
-K8S_CONTEXT_PATTERN='arn:aws:eks:us-west-2:853397791086:cluster/CLUSTERNAME-k8s-testnet'
+K8S_CONTEXT_PATTERN='arn:aws:eks:us-west-2:853397791086:cluster/libra-rustietest'
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
@@ -61,15 +61,7 @@ join_env_vars() {
 }
 
 kube_init_context () {
-  aws eks --region us-west-2 describe-cluster --name ct-0-k8s-testnet &>/dev/null || (echo "Failed to access EKS, try awsmfa?"; exit 1)
-  local highest_pool_index=$(($K8S_POOL_SIZE - 1))
-  local context=${K8S_CONTEXT_PATTERN/CLUSTERNAME/ct-${highest_pool_index}}
-  if kubectl config get-contexts ${context} &> /dev/null; then
-    return
-  fi
-  for ((i = 0; i < ${K8S_POOL_SIZE}; i++)); do
-    aws eks --region us-west-2 update-kubeconfig --name ct-${i}-k8s-testnet
-  done
+  aws eks --region us-west-2 describe-cluster --name libra-rustietest &>/dev/null || (echo "Failed to access EKS, try awsmfa?"; exit 1)
 }
 
 kube_select_cluster () {
@@ -257,7 +249,7 @@ sed -e "s/{pod_name}/${pod_name}/g" \
     ${DIR}/cluster_test_pod_template.yaml > ${specfile}
 
 echo "Using cluster : ${WORKSPACE}"
-context=${K8S_CONTEXT_PATTERN/CLUSTERNAME/${WORKSPACE}}
+context=${K8S_CONTEXT_PATTERN}
 kubectl --context=${context} apply -f ${specfile} || (echo "Failed to create cluster-test pod"; exit 1)
 kube_wait_pod ${pod_name} ${context}
 START_UTC=$(TZ=UTC date +"%Y-%m-%dT%H:%M:%SZ")
