[gha] e2e tests, sccache, cache, and documentation cleanup
Closes: #7180

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -6,10 +6,17 @@ on:
   pull_request:
     branches: [main, master, release-*, gha-test-*]
 
+defaults:
+  run:
+    shell: bash
+
+env:
+  max_threads: 16
+  pre_command: cd /opt/git/diem/
+
 jobs:
   prepare:
     runs-on: ubuntu-latest
-    continue-on-error: false
     outputs:
       changes-target-branch: ${{ steps.changes.outputs.changes-target-branch }}
       changes-base-githash: ${{ steps.changes.outputs.changes-base-githash }}
@@ -18,7 +25,6 @@ jobs:
       test-dev-setup: ${{ steps.dev-setup-sh-changes.outputs.changes-found }}
       test-website-build: ${{ steps.website-changes.outputs.changes-found }}
       test-non-rust-lint: ${{ steps.non-rust-lint-changes.outputs.changes-found }}
-      max-threads: "16"
     steps:
       - uses: actions/checkout@v2
         with:
@@ -57,7 +63,6 @@ jobs:
 
   dev-setup-sh-test:
     runs-on: ubuntu-latest-xl
-    continue-on-error: false
     timeout-minutes: 30
     needs: prepare
     if: ${{ needs.prepare.outputs.test-dev-setup == 'true' }}
@@ -73,7 +78,6 @@ jobs:
 
   non-rust-lint:
     runs-on: ubuntu-latest
-    continue-on-error: false
     timeout-minutes: 5
     needs: prepare
     if: ${{ needs.prepare.outputs.test-non-rust-lint == 'true'  }}
@@ -91,53 +95,59 @@ jobs:
           shellcheck docker/build_push.sh && \
           shellcheck docker/dockerhub_to_novi_ecr.sh
       - name: docker lints
-        run: |
-          hadolint docker/ci/github/Dockerfile && \
-          hadolint docker/ci/arch/Dockerfile && \
-          hadolint docker/ci/alpine/Dockerfile && \
-          hadolint docker/ci/centos/Dockerfile
+        uses: ./.github/actions/docker-checks
 
   lint:
     runs-on: ubuntu-latest-xl
     timeout-minutes: 30
-    continue-on-error: false
     needs: prepare
     if: ${{ needs.prepare.outputs.test-rust == 'true' }}
     container:
       image: libra/build_environment:github-1
+      volumes:
+        - "/home/runner/work/diem/diem:/opt/git/diem"
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
       - uses: ./.github/actions/build-setup
+      - uses: actions/cache@v2
+        with:
+          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
+          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+          restore-keys: "crates-${{ runner.os }}"
       - name: cargo lint
-        run: cargo x lint
+        run: $pre_command && cargo x lint
       - name: cargo clippy
-        run: cargo xclippy --workspace --all-targets
+        run: $pre_command && cargo xclippy --workspace --all-targets
       - name: cargo clippy tcb
-        run: cargo xclippy --members lec --members lsr --members key-manager
+        run: $pre_command && cargo xclippy --members lec --members lsr --members key-manager
       - name: cargo fmt
-        run: cargo xfmt --check
+        run: $pre_command && cargo xfmt --check
       - uses: ./.github/actions/build-teardown
 
   unit-test:
     runs-on: ubuntu-latest-xl
     timeout-minutes: 40
-    continue-on-error: false
     needs: prepare
     if: ${{ needs.prepare.outputs.test-rust == 'true' }}
     container:
       image: libra/build_environment:github-1
-    env:
-      max_threads: ${{ needs.prepare.outputs.max-threads }}
+      volumes:
+        - "/home/runner/work/diem/diem:/opt/git/diem"
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
           fetch-depth: 0 #get all the history!!!
       - uses: ./.github/actions/build-setup
+      - uses: actions/cache@v2
+        with:
+          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
+          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+          restore-keys: "crates-${{ runner.os }}"
       - name: run unit tests
-        run: cargo x test --jobs ${max_threads} --unit --changed-since "origin/$TARGET_BRANCH"
+        run: $pre_command && cargo x test --jobs ${max_threads} --unit --changed-since "origin/$TARGET_BRANCH"
         env:
           TARGET_BRANCH: ${{ needs.prepare.outputs.changes-target-branch }}
       - uses: ./.github/actions/build-teardown
@@ -145,36 +155,104 @@ jobs:
   e2e-test:
     runs-on: ubuntu-latest-xl
     timeout-minutes: 40
-    continue-on-error: false
     needs: prepare
     if: ${{ needs.prepare.outputs.test-rust == 'true' }}
     container:
       image: libra/build_environment:github-1
+      volumes:
+        - "/home/runner/work/diem/diem:/opt/git/diem"
+    strategy:
+      fail-fast: false
+      matrix:
+        runner: [0, 1] # set the env runners to the count below.
+    env:
+      runners: 2
+      E2E_RETRIES: 3
+      FLAKY_TESTS_FILE: /tmp/failures
+      MESSAGE_PAYLOAD_FILE: /tmp/message
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
       - uses: ./.github/actions/build-setup
+      - name: split tests
+        run: |
+          cd /opt/git/diem/
+          cargo x test --package smoke-test -- --list | \
+            grep "::" | sed 's/: .*$//' > e2e_tests
+          echo -e "Found $(wc -l e2e_tests) tests."
+          # Splits the e2e test via round robin in to ${runners} number of files with single digit extensions.
+          split -n r/${runners} -d -a 1 e2e_tests /tmp/tests.
+          rm e2e_tests
+          mv /tmp/tests.${{ matrix.runner }} /tmp/tests_to_run
+          echo -e "This runner will run these tests\n$(cat /tmp/tests_to_run)"
       - name: run e2e tests
-        run: cargo x test --package smoke-test -- --test-threads 2 --nocapture
+        run: |
+          set +e
+          num_fails=0
+          cd /opt/git/diem/
+          export RUST_BACKTRACE=full
+          failed_tests=
+          for target in $(cat /tmp/tests_to_run) ; do
+            retry=0
+            status=1
+            while [[ $status != 0 && $retry < ${E2E_RETRIES} ]]; do
+              cargo x test --package smoke-test -- $target --test-threads 1 --exact --nocapture
+              status=$?
+              retry=$((retry + 1))
+              if [[ $status != 0 ]] ; then
+                 echo Failed to execute $target, $retry times
+              fi
+              sleep 10
+            done
+            if [[ $status != 0 ]] ; then
+              num_fails=$((num_fails + 1))
+              echo failed to execute $target
+              failed_tests="${target}\n${failed_tests}"
+            elif [[ $retry > 1 ]]; then
+              echo "$target passed after $retry tries" >> ${FLAKY_TESTS_FILE}
+            fi
+          done
+          if [ -e ${FLAKY_TESTS_FILE} ]; then
+            msg="Found flaky tests\n$(cat ${FLAKY_TESTS_FILE})"
+            echo -e $msg
+            echo -e $msg > ${MESSAGE_PAYLOAD_FILE}
+          fi
+          if [[ $num_fails != 0 ]]; then
+            echo -e "$num_fails test(s) failed:\n${failed_tests}"
+          fi
+          exit $num_fails
+      - name: output failed tests.
+        run: |
+          if [[ -n ${MESSAGE_PAYLOAD_FILE} ]] && [[ -f " ${MESSAGE_PAYLOAD_FILE}" ]]; then
+            cat ${MESSAGE_PAYLOAD_FILE}
+          else
+            echo No errors.
+          fi
       - uses: ./.github/actions/build-teardown
 
   crypto-unit-test:
     runs-on: ubuntu-latest
     timeout-minutes: 20
-    continue-on-error: false
     needs: prepare
     if: ${{ needs.prepare.outputs.test-rust == 'true' }}
     container:
       image: libra/build_environment:github-1
+      volumes:
+        - "/home/runner/work/diem/diem:/opt/git/diem"
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
       - uses: ./.github/actions/build-setup
+      - uses: actions/cache@v2
+        with:
+          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
+          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+          restore-keys: "crates-${{ runner.os }}"
       - name: run crypto unit tests
         run: |
-          cd crypto/crypto
+          cd /opt/git/diem/crypto/crypto
           $CARGO $CARGOFLAGS test --features='vanilla-u64' --no-default-features
           $CARGO $CARGOFLAGS test --features='vanilla-u32' --no-default-features
       - uses: ./.github/actions/build-teardown
@@ -183,16 +261,22 @@ jobs:
   build-benchmarks:
     runs-on: ubuntu-latest-xl
     timeout-minutes: 30
-    continue-on-error: false
     needs: prepare
     if: ${{ needs.prepare.outputs.test-rust == 'true' }}
     container:
       image: libra/build_environment:github-1
+      volumes:
+        - "/home/runner/work/diem/diem:/opt/git/diem"
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
       - uses: ./.github/actions/build-setup
+      - uses: actions/cache@v2
+        with:
+          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
+          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+          restore-keys: "crates-${{ runner.os }}"
       - name: build benchmarks
         run: cargo x bench --no-run
       - uses: ./.github/actions/build-teardown
@@ -200,21 +284,26 @@ jobs:
   build-dev:
     runs-on: ubuntu-latest-xl
     timeout-minutes: 30
-    continue-on-error: false
     needs: prepare
     if: ${{ needs.prepare.outputs.test-rust == 'true' }}
     container:
       image: libra/build_environment:github-1
-    env:
-      max_threads: ${{ needs.prepare.outputs.max-threads }}
+      volumes:
+        - "/home/runner/work/diem/diem:/opt/git/diem"
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
       - uses: ./.github/actions/build-setup
-      - run: cargo xcheck -j ${max_threads} --members production
-      - run: cargo xcheck -j ${max_threads} --workspace --all-targets
+      - uses: actions/cache@v2
+        with:
+          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
+          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+          restore-keys: "crates-${{ runner.os }}"
+      - run: cd /opt/git/diem/ && cargo xcheck -j ${max_threads} --members production
+      - run: cd /opt/git/diem/ && cargo xcheck -j ${max_threads} --workspace --all-targets
       - run: |
+          cd /opt/git/diem
           rustup target add powerpc-unknown-linux-gnu
           cargo xcheck -j ${max_threads} -p transaction-builder -p move-vm-types --target powerpc-unknown-linux-gnu
       - uses: ./.github/actions/build-teardown
