[gha] single job if needed for bors

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -2,7 +2,7 @@ name: ci-test
 
 on:
   push:
-    branches: [auto, gha-test-*]
+    branches: [auto, canary, gha-test-*]
   pull_request:
     branches: [main, master, release-*, gha-test-*]
 
@@ -49,7 +49,7 @@ jobs:
         name: find shell/dockerfile changes
         uses: ./.github/actions/matches
         with:
-          pattern: 'Dockerfile$\|.sh$'
+          pattern: 'Dockerfile$\|.*.sh$'
       - id: dev-setup-sh-changes
         name: find dev-setup.sh/base docker image changes
         uses: ./.github/actions/matches
@@ -307,3 +307,45 @@ jobs:
           rustup target add powerpc-unknown-linux-gnu
           cargo xcheck -j ${max_threads} -p transaction-builder -p move-vm-types --target powerpc-unknown-linux-gnu
       - uses: ./.github/actions/build-teardown
+
+  success:
+    name: ci-test-success
+    runs-on: ubuntu-latest
+    timeout-minutes: 2
+    #always run this job even if needed jobs failed or are skipped.
+    if: ${{ always() }}
+    needs:
+      - prepare
+      - dev-setup-sh-test
+      - non-rust-lint
+      - lint
+      - unit-test
+      - e2e-test
+      - crypto-unit-test
+      - build-benchmarks
+      - build-dev
+    steps:
+      - run: |
+          echo prepare: ${{ needs.prepare.result }}
+          echo dev-setup-sh-test: ${{ needs.dev-setup-sh-test.result }}
+          echo non-rust-lint: ${{ needs.non-rust-lint.result }}
+          echo lint: ${{ needs.lint.result }}
+          echo unit-test: ${{ needs.unit-test.result }}
+          echo e2e-test: ${{ needs.e2e-test.result }}
+          echo crypto-unit-test: ${{ needs.crypto-unit-test.result }}
+          echo build-benchmarks: ${{ needs.build-benchmarks.result }}
+          echo build-dev: ${{ needs.build-dev.result }}
+          success="${{
+            needs.prepare.result=='success'
+            && (needs.dev-setup-sh-test.result=='success' || needs.dev-setup-sh-test.result=='skipped')
+            && (needs.non-rust-lint.result=='success' || needs.non-rust-lint.result=='skipped')
+            && (needs.lint.result=='success' || needs.lint.result=='skipped')
+            && (needs.unit-test.result=='success' || needs.unit-test.result=='skipped')
+            && (needs.e2e-test.result=='success' || needs.e2e-test.result=='skipped')
+            && (needs.crypto-unit-test.result=='success' || needs.crypto-unit-test.result=='skipped')
+            && (needs.build-benchmarks.result=='success' || needs.build-benchmarks.result=='skipped')
+            && (needs.build-dev.result=='success' || needs.build-dev.result=='skipped')
+          }}"
+          if [[ "$success" != "true" ]]; then
+            exit 1;
+          fi
